config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root to: "products#index"
resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :cards,only: [:index,:new,:show,:create,:destroy] do
      collection do
        post "buy", to: "cards#buy" 
      end
    end
end

resources :mypages,only: [:show] do
  resources :cards,only: [:index,:new,:show,:create,:destroy] do
    collection do
      post "buy", to: "cards#buy"
    end
  end
end

  # resources :purchases, only: [:index, :create]

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  collection do
    get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
  resources :purchases,only: [:index] do
    collection do
      get 'index', to: 'purchases#index'
      post 'done', to: 'purchases#done'
    end
  end
  end

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :purchases,only: [:index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'done', to: 'purchases#done'
      end
    end
    end
end

app/controllers/mypages_controller.rb
class MypagesController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/mypages_helper.rb
module MypagesHelper
end

app/views/mypages/_mypage-sidebar.html.haml
.left-content
  .left-content__bar
    %ul
      %li
        = link_to "マイページ", mypage_path 
        %br/
        %i.fa.fa-chevron-right
      %li
        = link_to "出品する", new_product_path
        %i.fa.fa-chevron-right
      %li
        = link_to "出品した商品-出品中", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "出品した商品-取引中", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "出品した商品-売却済み", "#"
        %i.fa.fa-chevron-right
      %li
        =link_to "購入した商品-取引中", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "購入した商品-過去の取引", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "評価一覧", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "ガイド", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "お問い合わせ", "#"
        %i.fa.fa-chevron-right

  .left-content__bar
    %h4 設定
    %ul.marginT-8px
      %li
        = link_to "支払い方法/カード登録", new_mypage_card_path(current_user.id)
        %i.fa.fa-chevron-right
      %li
        = link_to "住所変更", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "支払い方法", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "メール/パスワード"
        %i.fa.fa-chevron-right
      %li
        = link_to "本人情報", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to "電話番号の確認", "#"
        %i.fa.fa-chevron-right
      %li
        = link_to( destroy_user_session_path, method: :delete, class: "link_logout") do
          ログアウト
        %i.fa.fa-chevron-right

app/views/mypages/index.html.haml
= render "shared/header"  
.mypage-main-content
  = render 'mypages/mypage-sidebar'
  .a-right-content
    .a-right-content__block
      .a-right-content__block#back-img
      = image_tag 'mypage/user-icon.png', class:"user-icon"
      .a-right-content__block__user-name.bold #{current_user.nickname}
    .a-right-content__block
      %h4.a-right-content__block__title.middle.bold.back-silver 購入した商品
      %ul.a-right-content__block__tabs.back-gray
        %li.active
          %h4.mypage-transactions
            = link_to "取引中", root_path,class:"middle-center bold mypage-center"
        %li
          %h4
            = link_to "過去の取引", root_path,class:"middle-center bold mypage-center"
      %ul.a-right-content__block__object
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【送料込】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 7
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 3
                  .status-blue 出品中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品】THREE シマリンググローデュオ01
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 12
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 5
                  .status-blue 出品中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 「THREE シマリングリップジャム05」を購入しました。取引が完了しました。
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 5
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 7
                  .status-gray 取引完了
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品・未使用】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 10
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 8
                  .status-red 公開停止中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品・送料込み】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle ¥1,500
              %i.fa.fa-angle-right.fa-2x

app/views/mypages/show.html.haml
= render "shared/header"  
.mypage-main-content
  = render 'mypages/mypage-sidebar'
  .a-right-content
    .a-right-content__block
      .a-right-content__block#back-img
      = image_tag 'mypage/user-icon.png', class:"user-icon"
      .a-right-content__block__user-name.bold #{current_user.nickname}
    .a-right-content__block
      %h4.a-right-content__block__title.middle.bold.back-silver 購入した商品
      %ul.a-right-content__block__tabs.back-gray
        %li.active
          %h4.mypage-transactions
            = link_to "取引中", root_path,class:"middle-center bold mypage-center"
        %li
          %h4
            = link_to "過去の取引", root_path,class:"middle-center bold mypage-center"
      %ul.a-right-content__block__object
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【送料込】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 7
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 3
                  .status-blue 出品中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品】THREE シマリンググローデュオ01
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 12
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 5
                  .status-blue 出品中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 「THREE シマリングリップジャム05」を購入しました。取引が完了しました。
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 5
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 7
                  .status-gray 取引完了
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品・未使用】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-heart-o
                    .like-count 10
                  .a-right-content__block__object__link-box__body__detail--count-box
                    %i.fa.fa-comment-o
                    .comment-count 8
                  .status-red 公開停止中
              %i.fa.fa-angle-right.fa-2x
        = link_to root_path do
          %li
            .a-right-content__block__object__link-box
              .a-right-content__block__object__link-box__body
                .a-right-content__block__object__link-box__body--text 【新品・送料込み】THREE シマリングリップジャム08
                .a-right-content__block__object__link-box__body__detail.middle ¥1,500
              %i.fa.fa-angle-right.fa-2x