config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root to: "products#index"
resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :cards,only: [:index,:new,:show,:create,:destroy] do
      collection do
        post "buy", to: "cards#buy" 
      end
    end
end

resources :mypages,only: [:show] do
  resources :cards,only: [:index,:new,:show,:create,:destroy] do
    collection do
      post "buy", to: "cards#buy"
    end
  end
end

  # resources :purchases, only: [:index, :create]

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  collection do
    get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
  resources :purchases,only: [:index] do
    collection do
      get 'index', to: 'purchases#index'
      post 'done', to: 'purchases#done'
    end
  end
  end

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :purchases,only: [:index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'done', to: 'purchases#done'
      end
    end
    end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user

  validates :user_id, presence: true
  validates :customer_id, presence: true
  validates :card_id, presence: true
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card
  require 'payjp'
  
  def index
    if @card.present?
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(@card.customer_id)
      @card_info = customer.cards.retrieve(customer.default_card)
      @card_brand = @card_info.brand
      @exp_month = @card_info.exp_month.to_s
      @exp_year = @card_info.exp_year.to_s.slice(2,3) 
      case @card_brand
      when "Visa"
        @card_image = "VISA.png"
      when "JCB"
        @card_image = "JCB.jpg"
      when "MasterCard"
        @card_image = "MasterCard.png"
      when "American Express"
        @card_image = "AMERICAN EXPRESS.pngg"
      when "Diners Club"
        @card_image = "DinersClub.jpg"
      when "Discover"
        @card_image = "DISCOVER.jpg"
      end
    end
  end

  def new
    redirect_to action: "index" if @card.present?
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    if params['payjpToken'].blank?
      render "new"
    else
      customer = Payjp::Customer.create(
        description: 'test',
        email: current_user.email,
        card: params['payjpToken'],
        metadata: {user_id: current_user.id}
      )
      @card = Card.new(user_id: current_user.id, customer_id: customer.id, card_id: customer.default_card)
      if @card.save
        flash[:notice] = "支払い情報の登録が完了しました"
        redirect_to action: "index"
      else
        render 'new'
      end
    end
  end

  def destroy
    card = Card.where(user_id: current_user.id).first
    if card.blank?
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
    end
      redirect_to action: "new"
    # Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    # customer = Payjp::Customer.retrieve(@card.customer_id, @card.card_id)
    # customer.delete 
    # if @card.destroy 
    #   redirect_to action: "index", notice: "削除しました"
    # else
    #   redirect_to action: "index", alert: "削除できませんでした"
    # end
  end

  def show
    @product = Product.find(params[:id])
  end

  def buy
    @product = Product.find(params[:product_id])
    if @product.buy_user_id.present? 
      flash[:notice] = "すでに購入されています。" 
      redirect_back(fallback_location: root_path) 
    elsif @card.blank?
      # redirect_to action: "new"
      redirect_to root_path
      flash[:notice] = '購入にはクレジットカード登録が必要です/マイページから登録をお願い致します。'
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      Payjp::Charge.create(
      amount: @product.price,
      customer: @card.customer_id,
      currency: 'jpy',
      )
      if @product.update(buy_user_id: current_user.id)
        flash[:notice] = '購入しました。'
        redirect_to controller: 'products', action: 'show', id: @product.id
      else
        flash[:notice] = '購入に失敗しました。'
        redirect_to controller: 'products', action: 'show', id: @product.id
      end
    end
  end

  private
  def set_card
    @card = Card.where(user_id: current_user.id).first if Card.where(user_id: current_user.id).present?
  end


end
 

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_templatename.html.haml
= render "shared/header"  

= form_with url:cards_path, method: :post, html: { name: "inputForm" },class:"form" do |f|
  .form__upper
    =f.label :支払い方法
    .form__upper__group
      = f.label :カード番号
      %span.form-require 必須
      = f.text_field :card_number, name: "card_number", id:"card_number", type: "text", placeholder: '半角数字のみ', class: 'input-default', maxlength: "16"
      %ol
        = image_tag("/images/material/card-logo/VISA.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/MasterCard.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/SAISON.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/JCB.jpg", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/AMERICAN EXPRESS.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/DinersClub.jpg", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/DISCOVER.jpg", class: "form__upper__group__icon")
    .form__upper__group.exp
      .name
        = f.label :有効期限
        %span.form-require 必須
      = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]], {}, class: 'input-default harf', name: "exp_year", id:"exp_year"
      %span 年
      = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, class: 'input-default harf', name: "exp_month", id:"exp_month"
      %span 月
    .form__upper__group
      = f.label :セキュリティーコード
      %span.form-require 必須
      = f.text_field :cvc, name: "cvc", id:"cvc", class:"cvc", type: "text", placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', maxlength: "16"
    .form__upper__group
      %p.about
        %span
        = link_to 'カード裏面の番号とは？', root_path, class:'about__registered'
    .form__upper__group
      = f.submit '次へ進む', class: 'btn-default', id: "charge-form"
      
= render "shared/footer"  
= render "shared/sub_footer"  
= render "shared/sellbtn"

app/views/cards/index.html.haml
.creditcard__show
  .show__title
    登録クレジットカード情報
  .show__information
    .show__information--cardNo
      クレジット番号
      - if @card.present?
        .card__No
          = "**** **** **** " + @card_info.last4
          %br
        .show__information--limit
          有効期限
        .limit
          - exp_month = @card_info.exp_month.to_s
          - exp_year = @card_info.exp_year.to_s.slice(2,3)
          = exp_month + " / " + exp_year
          = link_to "削除する", new_mypage_card_path, method: :delete, class:"card-info__delete"
          = link_to "マイページに戻る", mypage_path(current_user.id), method: :get, calss: "card-info_delete"
      - else
        .new-card
          = button_to "クレジットカード新規登録",new_mypage_card_path,class: "new-card-btn", method: "get"

app/views/cards/new.html.haml
= render "shared/header"  

= form_with url:mypage_cards_path, method: :post, html: { name: "inputForm" },class:"form" do |f|
  .form__upper
    =f.label :支払い方法
    .form__upper__group
      = f.label :カード番号
      %span.form-require 必須
      = f.text_field :card_number, name: "card_number", id:"card_number", type: "text", placeholder: '半角数字のみ', class: 'input-default', maxlength: "16"
      %ol
        = image_tag("/images/material/card-logo/VISA.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/MasterCard.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/SAISON.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/JCB.jpg", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/AMERICAN EXPRESS.png", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/DinersClub.jpg", class: "form__upper__group__icon")
        = image_tag("/images/material/card-logo/DISCOVER.jpg", class: "form__upper__group__icon")
    .form__upper__group.exp
      .name
        = f.label :有効期限
        %span.form-require 必須
      = f.select :exp_year, [["19",2019],["20",2020],["21",2021],["22",2022],["23",2023],["24",2024],["25",2025],["26",2026],["27",2027],["28",2028],["29",2029]], {}, class: 'input-default harf', name: "exp_year", id:"exp_year"
      %span 年
      = f.select :exp_month, [["01",1],["02",2],["03",3],["04",4],["05",5],["06",6],["07",7],["08",8],["09",9],["10",10],["11",11],["12",12]],{}, class: 'input-default harf', name: "exp_month", id:"exp_month"
      %span 月
    .form__upper__group
      = f.label :セキュリティーコード
      %span.form-require 必須
      = f.text_field :cvc, name: "cvc", id:"cvc", class:"cvc", type: "text", placeholder: 'カード背面4桁もしくは3桁の番号', class: 'input-default', maxlength: "16"
    .form__upper__group
      %p.about
        %span
        = link_to 'カード裏面の番号とは？', root_path, class:'about__registered'
    .form__upper__group
      = f.submit '次へ進む', class: 'btn-default', id: "charge-form"
      
= render "shared/footer"  
= render "shared/sub_footer"  
= render "shared/sellbtn"

app/views/cards/show.html.haml
= render "shared/header" 

.confirm-complete
  .confirm-box
    .confirm-box__message
      .message_question
        購入を確定しますか？
    .confirm-box__image
      - @product.images.each do |image|
        = image_tag ("#{image.src}"),class:"product__image" 
    .confirm-box__name
      .name__confirm-name
        = @product.name
    .confirm-box__price
      .price__confirm-price
        = "￥#{@product.price.to_s}"
        (税込)
    .confirm-box__purchase
      .purchase__confirm-btn
        = button_to "購入完了", buy_product_cards_path(@product)

  
  = render "/shared/sub_footer"