config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: "users/sessions",
  }
  devise_scope :user do
    get 'addresses', to: 'users/registrations#new_address'
    post 'addresses', to: 'users/registrations#create_address'
  end
  root to: "products#index"
resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :cards,only: [:index,:new,:show,:create,:destroy] do
      collection do
        post "buy", to: "cards#buy" 
      end
    end
end

resources :mypages,only: [:show] do
  resources :cards,only: [:index,:new,:show,:create,:destroy] do
    collection do
      post "buy", to: "cards#buy"
    end
  end
end

  # resources :purchases, only: [:index, :create]

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
  collection do
    get 'category/get_category_children', to: 'products#get_category_children', defaults: { format: 'json' }
    get 'category/get_category_grandchildren', to: 'products#get_category_grandchildren', defaults: { format: 'json' }
    end
  resources :purchases,only: [:index] do
    collection do
      get 'index', to: 'purchases#index'
      post 'done', to: 'purchases#done'
    end
  end
  end

  resources :products,only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :purchases,only: [:index] do
      collection do
        get 'index', to: 'purchases#index'
        post 'done', to: 'purchases#done'
      end
    end
    end
end

app/models/product.rb
class Product < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :region
  has_many :images, dependent: :destroy
  accepts_nested_attributes_for :images, allow_destroy: true, update_only: true

  enum status: {
    新品、未使用: 0, 
    目立った傷や汚れなし: 1, 
    やや傷や汚れあり: 2, 
    傷や汚れあり: 3, 
    全体的に状態が悪い: 4
  }

  enum send_fee: {
    送料込み（出品者負担）: 0, 
    着払い（購入者）: 1
  }

  enum send_day: {
    １〜２日で発送: 0, 
    ２〜３日で発送: 1, 
    ４〜７日で発送: 2
  }

  belongs_to :category
  belongs_to :user, optional: true
  
  validates :name, presence: true,  length: { maximum: 40 }
  validates :description, presence: true, length: { maximum: 1000 }
  validates :category, presence: true
  validates :status, presence: true
  validates :send_fee, presence: true
  validates :region_id, presence: true
  validates :send_day, presence: true
  validates :price, presence: true, inclusion: 300..9999999
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :show, :update, :destroy]
  def index
    @products = Product.all.order("created_at DESC").limit(6)
    @images = Image.all.includes(:item)
  end

  def new
    @product = Product.new
    @product.images.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save!
      redirect_to root_path, notice: "出品しました"
    else
      render :new, notice: "出品できませんでした"
    end
  end

  def show
    @category = @product.category
  end
  
  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to root_path(@product.id), notice: '商品を編集しました'
    else
      redirect_to edit_product_path, notice: '商品を編集できませんでした'
    end
  end

  def destroy
    if @product.destroy
      redirect_to root_path, notice: "商品を削除しました"
    else
      redirect_to root_path, notice: "商品を削除出来ませんでした"
    end
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :description, :brand, :status, :send_fee, :region_id, :category_id, :send_day, :price, images_attributes: [:src, :_destroy, :id]).merge(user_id: current_user.id)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_footer.html.haml
%ul.subFooter__content__box
  %li.subFooter__content__box__comment
    プライバシーポリシー
  %li.subFooter__content__box__comment
    フリマ利用規約
  %li.subFooter__content__box__comment
    特定商取引に関する表記
%small.subFooter__content__copyright
  © Furima,inc.

app/views/products/_header.html.haml
= link_to root_path, class: 'subHeader__logo' do
  = image_tag("/images/material/logo/logo.png", alt: "furima")

app/views/products/destroy.html.haml
.footer
  .footer__image
    %h1 商品の削除が完了致しました。
    = link_to "一覧ページに戻る", "/"

app/views/products/edit.html.haml
.subHeader
  = render partial: 'header'

.contents
  = form_with model:@product, local:true do |f|
    
    .content
      .keyWordBox
        .keyWordBox__name
          出品画像
        .keyWordBox__type
          必須
      .uploadComment
        最大5枚までアップロードできます
      .post__drop__box__container
        .prev-content
          - @product.images.each do |image|
            .preview-box
              .upper-box
                = image_tag image.src.url, width: "112", height: "112", alt: "preview"
              .lower-box
                .delete-box
                  .delete-btn
                    %span 削除
        .label-content
          %label{for: "product_images_attributes_#{@product.images.length}_src", class: "label-box", id: "label-box--#{@product.images.length}"}
            %pre.label-box__text-visible クリックしてファイルをアップロード
        .hidden-content
          =f.fields_for :images do |i|
            = i.file_field :src, class: "hidden-field"
            = i.check_box :_destroy, class: "hidden-checkbox"
          - @product.images.length.upto(4) do |i|
            %input{name: "product[images_attributes][#{i}][src]", id: "product_images_attributes_#{i}_src", class: "hidden-field", type: "file"}
    .content
      .keyWordBox
        .keyWordBox__name
          出品名
        .keyWordBox__type
          必須
      = f.text_field :name, placeholder:"40文字まで", class: "textField"
      .keyWordBox
        .keyWordBox__name
          商品の説明
        .keyWordBox__type
          必須
      = f.text_area :description, class: "textArea"

    .content
      .content__comment
        商品の詳細
      .keyWordBox
        .keyWordBox__name
          カテゴリー
        .keyWordBox__type
          必須
      = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
      .sub
      .sub2
      .keyWordBox
        .keyWordBox__name
          ブランド
        .keyWordBox__typeSecond
          任意
      = f.text_field :brand, placeholder:"例) シャネル", class: "textField"
      .keyWordBox
        .keyWordBox__name
          商品の状態
        .keyWordBox__type
          必須
      = f.select :status, Product.statuses.keys,{include_blank: "選択してください"}

    .content
      .content__comment
        配送料について
      .keyWordBox
        .keyWordBox__name
          配送料の負担
        .keyWordBox__type
          必須
      = f.select :send_fee, Product.send_fees.keys,{include_blank: "選択してください"}
      .keyWordBox
        .keyWordBox__name
          発送元の地域
        .keyWordBox__type
          必須
      = f.collection_select :region_id, Region.all, :id, :name, {include_blank: "選択してください"}
      .keyWordBox
        .keyWordBox__name
          発送までの日数
        .keyWordBox__type
          必須
      = f.select :send_day, Product.send_days.keys,{include_blank: "選択してください"} 

    .content
      .content__comment
        価格 (¥300~9,999,999)
      .keyWordBox
        .keyWordBox__name
          販売価格
        .keyWordBox__type
          必須
        .keyWordBox__option
          ¥
          = f.number_field :price, class: "numberField"
      #commentSecond
        販売手数料 (10%)
        #commentSecond__score
      .content__commentSecond
        販売利益
        .content__commentSecond__score
      .contentBtn
        = f.submit "変更する", class: 'submitBtn'
        = link_to root_path, class: 'toplinkBtn' do
          もどる

.subFooter
  = render partial: 'footer'

app/views/products/index.html.haml
= render "shared/header"  

.main
  %section.mainVisual
    .cont
      %h2.cont__subtitle
        %br/
        人生を変えるフリマアプリ
      %p.cont__text
        FURIMAはだれでもかんたんに出品・購入できる
        %br/
        フリマアプリです
      .cont__btn
        =link_to "#", id:".aBtn" do
          %img{:src => "/images/material/download/app.png",class: 'aBtn'}/
        =link_to "#", id:".gBtn" do
          %img{:src => "/images/material/download/google.png",class: 'gBtn'}/
    .picture
  %section.topIntroduction
    %h2.subtitle
      FURIMAが選ばれる3つの理由
    %ul.lists
      %li.list
        .list__pict
          %span.number 1
          =image_tag("/images/material/pict/pict-reason-01.jpg")
        %h3.list__text
          %span 3分
          ですぐに出品
        %p.list__description
          スマホで入力するだけで簡単に出品できる！
      %li.list
        .list__pict
          %span.number 2
          =image_tag("/images/material/pict/pict-reason-02.jpg")
        %h3.list__text
          %span シンプル
          で使いやすい
        %p.list__description
          めんどくさい入力は必要なく、検索も購入もスムーズ！
      %li.list.list--last
        .list__pict
          %span.number 3
          =image_tag("/images/material/pict/pict-reason-03.jpg")
        %h3.list__text
          手数料
          %span 業界最安
        %p.list__description
          最大3%でお得に出品&amp;購入！
  %section.topMiddleDl
    .topMiddleDl__inner
      %h2.subtitle 会員数日本一位
      %p.text
        FURIMAは、フリマアプリで最も人気。
        %br/
        出品・購入回数も業界最多です！
        %br/
        ほしかったあの商品に出会えるかもしれません。
      .btn
        =link_to "#" do
          =image_tag("/images/material/download/app.png",class: 'aBtn')
        =link_to "#" do
          =image_tag("/images/material/download/google.png",class: 'gBtn')
  %section.topKeyFeatures
    %h2.head FURIMAの特徴
    .items
      %section.item
        %figure.item__img
          =image_tag("/images/material/icon/icon-01.png")
        %h3.item__subtitle 簡単に売り買いできる
        %p.item__detail
          スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
      %section.item
        %figure.item__img
          =image_tag("/images/material/icon/icon-03.png")
        %h3.item__subtitle 売上金は即日振込みに対応
        %p.item__detail
          午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
      %section.item
        %figure.item__img
          =image_tag("/images/material/icon/icon-04.png")
        %h3.item__subtitle 様々な支払いに対応
        %p.item__detail
          お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。
  %section.pickupbox 
    %h2.pickupbox--title ピックアップカテゴリー
    .pickupbox__category
      .pickupbox__category__head
        = link_to root_path do
          %h3.pickupbox__category__head--title  新規投稿商品
      .pickupbox__category__lists
        - @products.each do |product|
          = link_to product_path(product.id) do
            .pickupbox__category__list
              %figure.pickupbox__category__lists--image
                = image_tag product.images.first.src.url
              .pickupbox__category__list--text
                %h3.name 
                  = product.name
                .syosai
                  %ul
                    %li
                      = product.price 
                      円
                    %li
                      %i.fa  
                      ★0
                  %p.zeikomi (税込)
              - if product.buy_user_id.present? 
                .items-box_photo__sold
                  .items-box_photo__sold__inner
                    SOLD

= render "shared/footer"  
= render "shared/sub_footer"  
= render "shared/sellbtn"

app/views/products/new.html.haml
.subHeader
  = render partial: 'header'
  
.contents
  = form_with model:@product, local:true do |f|
    
    .content
      .keyWordBox
        .keyWordBox__name
          出品画像
        .keyWordBox__type
          必須
      .uploadComment
        最大5枚までアップロードできます
      .post__drop__box__container
        .prev-content
        .label-content
          %label{for: "product_images_attributes_0_src", class: "label-box", id: "label-box--0"}
            %pre.label-box__text-visible クリックしてファイルをアップロード
        .hidden-content
          = f.fields_for :images do |i|
            = i.file_field :src, class: "hidden-field"
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][1][src]", id: "product_images_attributes_1_src" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][2][src]", id: "product_images_attributes_2_src" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][3][src]", id: "product_images_attributes_3_src" }
            %input{class:"hidden-field", type: "file", name: "product[images_attributes][4][src]", id: "product_images_attributes_4_src" }
      
    .content
      .keyWordBox
        .keyWordBox__name
          出品名
        .keyWordBox__type
          必須
      = f.text_field :name, placeholder:"40文字まで", class: "textField"
      .keyWordBox
        .keyWordBox__name
          商品の説明
        .keyWordBox__type
          必須
      = f.text_area :description, class: "textArea"

    .content
      .content__comment
        商品の詳細
      .keyWordBox
        .keyWordBox__name
          カテゴリー
        .keyWordBox__type
          必須
      = f.collection_select :category_id, Category.where(ancestry: nil), :id, :name, {prompt: '---'}, {id: 'parent_category'}
      .sub
      .sub2
      .keyWordBox
        .keyWordBox__name
          ブランド
        .keyWordBox__typeSecond
          任意
      = f.text_field :brand, placeholder:"例) シャネル", class: "textField"
      .keyWordBox
        .keyWordBox__name
          商品の状態
        .keyWordBox__type
          必須
      = f.select :status, Product.statuses.keys,{include_blank: "選択してください"}

    .content
      .content__comment
        配送料について
      .keyWordBox
        .keyWordBox__name
          配送料の負担
        .keyWordBox__type
          必須
      = f.select :send_fee, Product.send_fees.keys,{include_blank: "選択してください"}
      .keyWordBox
        .keyWordBox__name
          発送元の地域
        .keyWordBox__type
          必須
      = f.collection_select :region_id, Region.all, :id, :name, {include_blank: "選択してください"}
      .keyWordBox
        .keyWordBox__name
          発送までの日数
        .keyWordBox__type
          必須
      = f.select :send_day, Product.send_days.keys,{include_blank: "選択してください"} 

    .content
      .content__comment
        価格 (¥300~9,999,999)
      .keyWordBox
        .keyWordBox__name
          販売価格
        .keyWordBox__type
          必須
        .keyWordBox__option
          ¥
          = f.number_field :price, class: "numberField"
      #commentSecond
        販売手数料 (10%)
        #commentSecond__score
      .content__commentSecond
        販売利益
        .content__commentSecond__score
      .contentBtn
        = f.submit "出品する", class: 'submitBtn'
        = link_to root_path, class: 'toplinkBtn' do
          もどる

.subFooter
  = render partial: 'footer'

app/views/products/show.html.haml
.PcHeader
  .headerInner
    .mainheader
      %h1.icon
        =link_to "/" do
          =image_tag("/images/material/logo/logo.png")
      .searchBox
        %form{"accept-charset" => "UTF-8", :action => "#", :method => "get"}
          %input{:name => "utf8", :type => "hidden", :value => "✓"}/
          %input#searchInput.searchBox--input{:name => "key", :placeholder => "キーワードから探す"}/
          %button{:type => "submit"}
            .searchBox__icon
              =image_tag("/images/material/icon/icon-search 1.png")
          %input{:name => "authenticity_token", :type => "hidden", :value => "K2GGkTFbGuaQPfsXR+fEectrW4VVhp66jzRtgvDH3bIKznrDVWPSPMhrusk1perI3Fz2yUXaDuHqZZQjQaUuxQ=="}/
      %ul.resultLists
    .nav
      %ul.listsLeft
        %li.listsLeft__item.listsLeft__item--first
          =link_to "カテゴリー" ,"#",id: "catBtn"  
          .tree.displayNone
            %ul.categoryTree
              %li.categoryTree--item
                =link_to "レディース","#" ,id:"#1"
              %li.categoryTree--item
                =link_to "メンズ","#" ,id:"#2"
              %li.categoryTree--item
                =link_to "ベビー・キッズ","#" ,id:"#3"
              %li.categoryTree--item
                =link_to "インテリア・住まい・小物","#" ,id:"#4"
              %li.categoryTree--item
                =link_to " 本・音楽・ゲーム","#" ,id:"#5"
              %li.categoryTree--item  
                =link_to "おもちゃ・ホビー・グッズ","#" ,id:"#6"
              %li.categoryTree--item
                =link_to "コスメ・香水・美容","#" ,id:"#7"
              %li.categoryTree--item
                =link_to "家電・スマホ・カメラ","#" ,id:"#8"
              %li.categoryTree--item
                =link_to "スポーツ・レジャー","#" ,id:"#9"
              %li.categoryTree--item
                =link_to "ハンドメイド","#" ,id:"#10"
              %li.categoryTree--item
                =link_to "チケット","#" ,id:"#11"
              %li.categoryTree--item
                =link_to "自動車・オートバイ","#" ,id:"#12"
              %li.categoryTree--item
                =link_to "その他","#" ,id:"#13"  
        %li.listsLeft__item
          =link_to "ブランド" ,"#",id: "brandBtn"  
          %ul.brandsPulldown.displayNone
      %ul.listsRight
        %li.listsRight__item.listsRight__item--login
          =link_to "ログイン" ,"#"
        %li.listsRight__item.listsRight__item--new
          =link_to "新規会員登録" ,"#"
        
  %nav.breadCrumbs
    %ul
      %li
        =link_to "FURIMA", "#"
      %li
        %i.fa.fa-angle-right
      %li
        =link_to "#{@product.category.name}", "#"
      %li
        %i.fa.fa-angle-right
      %li
        =link_to "#{@category.name}", "#"
      -# %li
      -#   %i.fa.fa-angle-right
      -# %li
      -#   =link_to "ノーカラージャケット", "#"
      %li
        %i.fa.fa-angle-right
      %li
        %p
        = @product.name
  .main
    .showMain
      .contentLeftqq
      .contentRight
        .topContent
          .itemBox
            %h2.itemBox__name 
              = @product.name
            = image_tag("#{@product.images[0].src.url}", width: 300, height:500)
            %div.imgs
              %ul
              - @product.images.each do |image|
                %li.imag
                  = image_tag("#{image.src.url}")
            .itemBox__body
              -# %ul
              -#   %li
              -#     =image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png")
              -#     %ul
              -#       %li
              -#         =image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/10/a004.png")
              -#       %li
              -#         =image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/11/a005.png")
              -#       %li
              -#         =image_tag("https://s3-ap-northeast-1.amazonaws.com/mercarimaster/uploads/captured_image/content/12/a006.png")
            .itemBox__price
              %span
                = @product.price
              .itemBox__price-detail
                %span
                  (税込)
                %span
                  送料込み
            .itemDetail
              = @product.description
            .table
              %table
                %tbody
                  %tr
                    %th 出品者
                    %td 
                      = @product.user.nickname
                  %tr
                    %th カテゴリー
                    %td
                      =link_to "#{@product.category.name}", "#"
                      %br/
                      =link_to "ジャケット/アウター", "#"
                      -# %br/
                      -# =link_to "ノーカラージャケット", "#"
                  %tr
                    %th ブランド
                    %td
                      = @product.brand
                  %tr
                    %th 商品のサイズ
                    %td 無し
                  %tr
                    %th 商品の状態
                    %td
                      = @product.status
                  %tr
                    %th 配送料の負担
                    %td
                      = @product.send_fee
                  %tr
                    %th 発送元の地域
                    %td
                      =link_to "#{@product.region.name}", "#"
                  %tr
                    %th 発送日の目安
                    %td
                      = @product.send_day
            .optionalArea
              %ul
                %li#likeBtn.optionalBtn.likeBtn
                  %i.fa.fa-star
                  お気に入り 0
              %ul.button
                - if user_signed_in? && current_user.id == @product.user_id
                  %li.button2
                    =link_to "削除", product_path(@product.id), method: 'delete' ,class: :"purchase"
                  %li.button2
                    =link_to "編集", edit_product_path(@product.id), class: :"purchase"
                - else
              -if user_signed_in? && current_user.id != @product.user_id
                %li.button2
                =link_to "購入", product_card_path(current_user.id), class: :"purchase"
              - else
              %ul.optional
                %li.optionalBtn
                  %a{:href => "#"}
                    %i.fa.fa-flag
                    不適切な商品の通報         
          .commentBox
            %ul.commentContents
            %form#new_comment.new_comment{"accept-charset" => "UTF-8", :action => "#", :method => "post"}
              %input{:name => "utf8", :type => "hidden", :value => "✓"}/
              %input{:name => "authenticity_token", :type => "hidden", :value => "jru3jR2f28vZNa3MYe39+9JeZm8/fpkYlrB6h4Ol5M1iGR61ETq8DaG1dee4ayayno2kiHCdhkQNNSCf9FbWWQ=="}/
              %textarea#comment_body{:name => "comment[body]", :required => "required"}
              %p.noticeMsg
                相手のことを考え丁寧なコメントを心がけましょう。
                %br/
                不快な言葉遣いなどは利用制限や退会処分となることがあります。
              %br/
              %button.commentBtn{:name => "button", :type => "submit", :url => "#"}
                %i.fa.fa-comment
                コメントする
        -# %ul.links
        -#   %li
        -#     =link_to "#" do
        -#       %i.fa.fa-angle-left
        -#       %span
        -#       前の商品
        -#   %li
        -#     =link_to "#" do
        -#       %span 後ろの商品
        -#       %i.fa.fa-angle-right
        -# .relatedItems
        -#   =link_to "#" "メンズをもっと見る"
        -#   .productLists

= render "shared/footer"  
= render "shared/sub_footer"  
= render "shared/sellbtn"
-#   %aside.appBanner
-#     .inner
-#       %h2.inner__title だれでもかんたん、人生を変えるフリマアプリ
-#       %p.inner__text 今すぐ無料ダウンロード！
-#       .inner__icon
-#         =link_to "#" do
-#           =image_tag("/images/material/download/app.png",class: '.linkIcon.aBtn')
-#         =link_to "#" do
-#           =image_tag("/images/material/download/google.png",class: '.linkIcon.gBtn')
-#   .footer
-#     %ul.contents
-#       %li.content
-#         %h2.content__head FURIMAについて
-#         %ul
-#           %li
-#           =link_to "#" do
-#             会社概要（運営会社）
-#         %li
-#           =link_to "#" do
-#             プライバシーポリシー
-#         %li
-#           =link_to "#" do
-#             FURIMA利用規約
-#         %li
-#           =link_to "#" do
-#             ポイントに関する特約
-#       %li.content
-#         %h2.content__head FURIMAを見る
-#         %ul
-#           %li
-#           =link_to "#" do
-#             カテゴリー一覧
-#         %li
-#           =link_to "#" do
-#             ブランド一覧
-#       %li.content
-#         %h2.content__head ヘルプ＆ガイド
-#         %ul
-#           %li
-#             =link_to "#" do
-#               FURIMAガイド
-#           %li
-#             =link_to "#" do
-#               FURIMAロゴ利用ガイドライン
-#           %li
-#             =link_to "#" do
-#               お知らせ
-#     .footer__logo
-#     =link_to "/" do
-#       =image_tag("/images/material/logo/logo-white.png")
-#   %p © FURIMA
-# = link_to "#" do
-#   .purchaseBtn
-#     %span.purchaseBtn__text 出品する
-#     = image_tag("/images/material/icon/icon_camera.png")